### ISSUE TITLE
Update immutable contract variables to SNAKE_CASE

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1012]
# Motivation

Small linting update

# Details

lint:sol warns that immutable variables should use SNAKE_CASE:
![Image 2024-01-13 at 12 50 08](https://github.com/privacy-scaling-explorations/maci/assets/8097623/1209848d-cffe-442f-b7b8-1785c4cc36ec)

Relates to updates in #1008

**Comment by ctrlc03** [comment]
@samajammin perhaps we can close once we merge this #1083 - https://github.com/privacy-scaling-explorations/maci/blob/5be0b71fb0188d3eb0a5876ceb50c7d505b6c326/.solhint.json#L10 disables this rule which (at least imo) makes the code nicer than a bunch of capital snake case vars.

**Comment by ctrlc03** [comment]
@samajammin what you think of the above suggestion?

**Comment by ctrlc03** [comment]
I'll close this for now, but feel free to re-open if you believe that muting the warning is a not a good enough resolution for this
