### ISSUE TITLE
genLocalState is missing from maci-cli

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#1034]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am not running a deprecated version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

genLocalState should be exported as as other cli command like genProof

https://github.com/privacy-scaling-explorations/maci/blob/dev/cli/ts/index.ts#L553

# Current Behavior

genLocalState is not available for import from the maci-cli package

## Context

- MACI version: 0.0.0-ci.ae1f52e
- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ctrlc03** [comment]
fixed by #1038
