### ISSUE TITLE
MACI benchmarks

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#1081]
# Prerequisites

- [x] I checked to make sure that this request has not already been filed

# Motivation

As a user and developers I want to know how much time and cost it takes to use MACI. I should be aware of the efficiency and costs (both time and gas cots) that I could incur on when using MACI (primary tasks - deployment, voting, proving).

# Details

We have examples on how to write benchmarks

Is this for all packages? No, benchmarks for main tasks
- contract deployment
- signup
- message posting
- merging trees (incrementally larger number of users)
- submitting proofs (incrementally larger batches & number of batches)

Implement benchmarks for the following:
- contracts
  - [ ] Contract deployments costs
  - [ ] Contract usage costs per function
  - [ ] Coordinator costs for merging signups and messages
  - [ ] Coordinator costs for submitting proofs and commitments
- proof generation
  - [ ] Generating proofs of message processing
  - [ ] Generating proofs of vote tallying

What is the final deliverable?
- tools/code that anyone can run & tweak
- GH action that can be run in CI: monitor how changes to code affect the benchmarks
- documentation of these benchmarks (CSV format or similar?)

**Comment by samajammin** [comment]
Closing in favor of #1194 #1195 #1196 #1197
