### ISSUE TITLE
[circuits] Negative votes in MACI

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/maci#109]
## Motivation

In the book "Radical Markets" page 119, negative votes are proposed as a cheaper way to let a voter's favorite candidate stands out from a less favorable one.

To show why it's cheaper, consider a 2 candidate situation, and a voter Alice prefers Catherine over Carl. To make Catherine win Carl by 2 votes, Alice could

- vote +2 for Catherine, which costs 4 voice credits, or
- vote +1 for Catherine and -1 for Carl, which costs 2 voice credits only.

The result is useful in the situation that you have 3 candidates, the first two are widely loved by one camp of voters and hated by another, and the third is less hated but also not popular enough.

In the positive vote only situation, the voters would strategically vote the first two but not the third, to prevent the hated one winning.

But with the negative vote situation, the votes expect the first two get almost equally positive and negative votes and the third one could stand out. The voting dynamic is studied in [this paper](https://www.ssrn.com/abstract=3319508).

## Possible design choices in MACI

Thanks to @weijie for writing this section.

Two ways are possible to implement negative votes in MACI. We demonstrate this with examples.

Alice has 99 voice credits
Bob has 99 voice credits

Vote options: party A and party B

### Possibility 1 (hides information. e.g. the fact that a vote is polarised)

Bob votes for party A with 81 positive voice credits.
Party A now has +9 votes.

Alice does not like party A. She votes for party A with 36 negative voice credits.
Party A now has (+9) + (-6) = +3 votes.

Final tally = [3, 0]

### Possibility 2 (shows information, e.g. the fact that a vote is polarised)

Bob votes for party A with 81 positive voice credits.
Party A now has 9 positive votes and 0 negative votes.

Alice does not like party A. She votes for party A with 36 negative voice credits.

Party A now has 9 positive votes and 6 negative votes.

Final tally = [(9, 6), (0, 0)]

### Discussion

In Possibility 1 we have to worry about the overflow/underflow. Say, if party A only has -6 votes, what would the result look like? 

The Possibility 2 we tally the positive vote and negative votes in a different array. We don't have to worry about the overflow/underflow in this case.

### Circuit is happy with negative inputs?

Consider this circuit. Input `{ 'a': -1, 'b': 4 }` would gives witness `[ 1n, -4n, -1n, 4n ]`

```
 template Multiplier() {
       signal private input a;
       signal private input b;
       signal output c;
       
       c <== a*b;
   }

component main = Multiplier();

```

This either means the current circuit support negative vote natively or we have to handle the range of input values carefully.

**Comment by ctrlc03** [comment]
Closing this for now as previous work on negative vote was never merged in. Can re-open if a new proposal for such feature is proposed (maybe as an extension of MACI)
