### ISSUE TITLE
Signups after logs are fetched would cause proofs to not verify on chain

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#1091]
Currently, if a user is able to sign up after a poll logs have been fetched locally, the number of signups on the MACI contract would change, causing a discrepancy between the data fetched offhcain and the one on chain. 

A fix could be to store the number of signups at the time that the poll completed (when `mergeMaciStateAq` is run) and then use it as a source of truth. This could also enable another Poll to run at the same time from the same MACI instance, where users won't have to signup twice (for instance)

**Comment by samajammin** [comment]
> Currently, if a user is able to sign up after a poll logs have been fetched locally, the number of signups on the MACI contract would change, causing a discrepancy between the data fetched offhcain and the one on chain.

Does this cause message process / tallying to fail? So a Poll would be unable to finalize?

**Comment by ctrlc03** [comment]
> > Currently, if a user is able to sign up after a poll logs have been fetched locally, the number of signups on the MACI contract would change, causing a discrepancy between the data fetched offhcain and the one on chain.
> 
> Does this cause message process / tallying to fail? So a Poll would be unable to finalize?

Correct, as from within the Poll contract, we get the number of signups from maci: https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Poll.sol#L236 -> in MP we use it in several places while processing message batches commitments and proofs https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L98 , https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L167 etc.
