### ISSUE TITLE
Implement wallet connection for demo app

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci#1098]
### Description

As a user I'd like to connect my ethereum wallet and interact with the demo app.

### Acceptance criteria

- [ ] Integrate https://github.com/WalletConnect/web3modal
- [ ] Add UI for main wallet info: account, native token balance, network, icon

**Comment by samajammin** [comment]
@0xmad curious why you'd go with `web3modal` - have you used in before? Have you compared to alternatives? e.g. I see a lot of projects using https://www.rainbowkit.com/ now. I haven't personall followed developments closely across Ethereum Wallet integration tools...

**Comment by samajammin** [comment]
I suppose one consideration/dependency here is also [#1099](https://github.com/privacy-scaling-explorations/maci/issues/1099), in terms of if we decide to fork a frontend vs. build our own...

**Comment by 0xmad** [comment]
Yes, I have used web3modal and web3-react. If we use fork repo we don't need this task.

**Comment by samajammin** [comment]
Closing this out, already solved in the EasyRetroPGF codebase: https://github.com/privacy-scaling-explorations/maci-rpgf/
