### ISSUE TITLE
Additional event data fields

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/maci#1242]
# Motivation
Feedback from ETHGlobal Circuit Breaker:
"While playing around withe event handling, I think there are a few absent data fields, which need to be indexed - like when indexing Topup event, there is no stateIndex and credit "

# Details
Add stateIndex and credit to the Topup event.

**Comment by ctrlc03** [comment]
Gonna close this as the state index and credit can be taken from the message field emitted inside the Topup eventhttps://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Poll.sol#L173 -> conversation: https://github.com/privacy-scaling-explorations/maci/pull/1203#discussion_r1526362892

Feel free to re-open if I'm misunderstanding smth :)
