### ISSUE TITLE
CLI: Example Keypairs error

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/maci#1244]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am not running a deprecated version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

# Expected Behavior

I want to be able to run [CLI commands](https://maci.pse.dev/docs/cli) successfully and without errors.

# Current Behavior

"I tried to manually run these scripts with the following keypair (https://maci.pse.dev/docs/cli#scenario), but it respond incorrect keypair"

**Comment by ctrlc03** [comment]
fixed by #1246
