### ISSUE TITLE
docs: add links to the source code of the relevant smart contracts

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1253]
# Motivation

As a developer reading the documentation to learn about MACI, I'd like to be able to easily view the source code

# Details

For each smart contract documentation page, include a link to the corresponding source code

e.g. for this contract:
https://maci.pse.dev/docs/solidity-docs/gatekeepers/EASGatekeeper

There should be a link to "view the code" which goes to:
https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/gatekeepers/EASGatekeeper.sol

**Comment by Ayoseun** [comment]
Can you assign this to me

**Comment by ctrlc03** [comment]
> Can you assign this to me

Thanks for the interest in working on this! assigned you! ps I just updated (https://github.com/privacy-scaling-explorations/maci/pull/1300) the `smart contracts` doc page with more up to date info, so might be worth waiting for this to be merged and start from there

**Comment by Ayoseun** [comment]
Okay, thanks.

**Comment by samajammin** [comment]
Thanks for taking this on @Ayoseun! Let us know how we can help support 😄

**Comment by aguzmant103** [comment]
Hi @Ayoseun ! Do you have any update on this task progress?

**Comment by ctrlc03** [comment]
@Ayoseun are there any updates on this? we might have to un-assign you soon (~1 week) if you do not reply, so that someone else can pick it up instead 🙂

**Comment by ctrlc03** [comment]
@Ayoseun Due to inactivity on this thread we will be un-assigning you for now, but we welcome you to re-engage with the project as you find a suitable issue to work on. Thanks for your initial interest to contribute to MACI and looking forward to any future contribution
