### ISSUE TITLE
docs: redesign blog index page

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1258]
# Motivation

As a visitors to https://maci.pse.dev/blog I want to easily navigate and discover blog posts

# Details

Currently the blog index page feels awkward: it lists the entire post of every single blog post, which makes it unclear if I'm viewing the page of a specific post or the index of all posts.

I suggest we create some simple view that shows short previews of each posts that can easily be scrolled through...

e.g. like these cards: https://mirror.xyz/privacy-scaling-explorations.eth or https://blog.ethereum.org/

e.g. or simple title, post snippets, and "read more" links https://stripe.com/blog/engineering

**Comment by ctrlc03** [comment]
> Hi, I'd like to tackle this, can you please assign me.

hey @mabsattar thanks for your interest to work on this, just assigned you!!

**Comment by samajammin** [comment]
Thanks @mabsattar! Let us know how we can help support. Appreciate you taking this on 🙏

**Comment by mabsattar** [comment]
@samajammin , thank you for assigning me, I'll make sure to reach you out if I need any help on this.

**Comment by ctrlc03** [comment]
@mabsattar wanted to check in to see if this was something you're still working on, and if you needed any help at all in case🙂

**Comment by mabsattar** [comment]
@ctrlc03  Hi, sorry I wasn't available since last month, I'll start working on it, and will try to complete it this week(this would be my first time building cards in ts), I would want to know should I be using any images for cards? if so can you please help me with that.

**Comment by ctrlc03** [comment]
> @ctrlc03 Hi, sorry I wasn't available since last month, I'll start working on it, and will try to complete it this week(this would be my first time building cards in ts), I would want to know should I be using any images for cards? if so can you please help me with that.

no worries!! I think any imagine will do for now, we can then get some custom made for each blogpost! let's use this https://github.com/privacy-scaling-explorations/maci/blob/dev/website/static/img/maci-card.png maybe

**Comment by mabsattar** [comment]
@ctrlc03 Noted, I'll try to push the code as soon as possible.

**Comment by mabsattar** [comment]
@ctrlc03 I sent a PR, will implement images on it later, also let me know if there's any changes needed in that. I'll also try to keep the blog page update with cards.
