### ISSUE TITLE
Modularize VkRegistry to allow storing different versions of vkeys and different flavors

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#1353]
The current design of the VkRegistry does not allow the same contract to be re-used for different vkeys for the same param combination, and neither allows a single MACI instance to run both qv and non qv rounds. 

A new design could be implemented where each vkey is stored with a version number (maci release version) to allow for a single deployment across chain, and re-use by every protocol integrating maci.

**Comment by samajammin** [comment]
Interesting! Do we know if there are any established patterns that projects in the space have used around this?
