### ISSUE TITLE
Add documentation of gatekeepers

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1382]
# Motivation

I find myself often sharing a link to our gatekeeper contracts:
https://github.com/privacy-scaling-explorations/maci/tree/dev/contracts/contracts/gatekeepers

But there's no README on this directory or page in the [MACI documentation](https://maci.pse.dev/docs/introduction) that explains how gatekeepers work

# Details

Create a new documentation page that explains gatekeepers, how they work, how they can be configured, and how someone might build their own custom gatekeeper contract to use MACI in a new way. More broadly it might be worth having this page explain how identity/authentication/access control happens in MACI, how MACI doesn't aim to solve this problem directly but relies on other solutions (e.g. EAS, Hats Protocol, Gitcoin Passport, whatever solution) to manage the identity & how the MACI gatekeeper contract then uses that identity system or authentication process to register users as eligible to vote.

**Comment by iusssmanovv** [comment]
nice
