### ISSUE TITLE
Create a Gitcoin Passport gatekeeper

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#1444]
# Motivation

MACI polls have been run that e.g. enforce voters to hold a certain NFT or to have received a specific EAS attestation. We want to continue to expand the configurability of MACI operators to set eligibility requirements.

We think a great piece of functionality would be to have a Gitcoin Passport gatekeeper contract where operators can set certain criteria (e.g. a score threshold)

# Details

Create a `PassportGatekeeper` contract that can configure a Passport score threshold

**Comment by ctrlc03** [comment]
> Looking quickly at the Passport docs:
> https://docs.passport.xyz/building-with-passport/smart-contracts/overview

> It appears the on-chain score is posted via an EAS attestation, so perhaps a custom contract is not needed here. We  > should explore if this could be accomplished using our existing [EASGatekeeper](https://github.com/privacy-scaling-> explorations/maci/blob/dev/contracts/contracts/gatekeepers/EASGatekeeper.sol) contract

I think we should have a separate contract, Gitcoin provides a custom decoder contract which can be used to get the score given an address, no need to go through the EAS attestation. That way we can keep all of our gatekeepers as lean as possible.

Though I think we can also have another gatekeeper which accepts signups from users with certain stamps only, something fun to discuss
