### ISSUE TITLE
Edit or remove the warning message of docusaurus

### ISSUE THREAD

**Issue by kittybest** [privacy-scaling-explorations/maci#1471]
# Prerequisites

Please answer the following question for yourself before submitting a feature request.

- [ ] I checked to make sure that this request has not already been filed

# Motivation & Details

<img width="856" alt="image" src="https://github.com/privacy-scaling-explorations/maci/assets/9023842/d0024c9f-8f5f-4dd3-8dd4-72877956f71a">

This message is kind of misleading, we actually are still updating the documents of v1.2, besides the latest version.

---
Make sure that you have reviewed [MACI's Contributor Guidelines](https://maci.pse.dev/docs/contributing)

**Comment by ctrlc03** [comment]
I found this: https://github.com/facebook/docusaurus/blob/525b0c2b5b55cc965de92ddeaac79d6fe6c62aea/packages/docusaurus-theme-classic/src/theme/DocVersionSuggestions/index.tsx#L53 
but couldn't find a way to actually fully customize the message

**Comment by wildanvin** [comment]
Hello, 
I would like to work on this issue please

**Comment by ctrlc03** [comment]
> Hello, I would like to work on this issue please

Nice thank you very much. Have assigned you

**Comment by wildanvin** [comment]
Hello,

I was doing some research and found that [Docusaurus](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#VersionsConfig) only has the options of `none`, `unreleased` and `unmaintained` for the versioning banner. So it is not possible to add a custom banner. 

What I did was to remove the banner entirely and just add an info message in the `introduction.md` and `circuits.md` (where I think the info message is more relevant)

The message that I am thinking is: "Version 1.2.4 of MACI's circuits has been audited and includes zKeys that have completed a trusted setup. v2 will also undergo this process soon".

This is what it looks like with said changes:

![image](https://github.com/user-attachments/assets/6cc99734-36fd-4103-8e27-110d70e60deb)

![image](https://github.com/user-attachments/assets/5e7affc1-1675-4349-89c2-3431679932cb)

Please let me know what do you think

**Comment by ctrlc03** [comment]
> The message that I am thinking is: "Version 1.2.4 of MACI's circuits has been audited and includes zKeys that have completed a trusted setup. v2 will also undergo this process soon".
> 
> This is what it looks like with said changes:

Nice!! I think we can go ahead with this, but maybe instead of this message it could be something along the lines of: "For a more secure and stable protocol, please refer to MACI v2.x" - and have this on the introduction page 

Thanks so much for this 🙏

**Comment by wildanvin** [comment]
Great! I will change the message and submit the PR a bit later today
