### ISSUE TITLE
Fix broken links with new docs page

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci#1513]
New doc pages break links on readme and other places.

**Comment by ctrlc03** [comment]
> New doc pages break links on readme and other places.

please could you add some details?

**Comment by crisgarner** [comment]
As we changed the docs, some links were broken, and most of the issues were on the maci-rpgf repo and where fixed here by attaching the docs to the version used https://github.com/privacy-scaling-explorations/maci-rpgf/pull/142
