### ISSUE TITLE
Gas Price miscalculated on deploy 

### ISSUE THREAD

**Issue by crisgarner** [privacy-scaling-explorations/maci#1563]
# Expected Behavior

Set gas settings on hardhat locally. 

# Current Behavior

At some point the code uses the function getFeeData() directly from the ethersjs package, instead of the hardhat-configured-etherjs instance.

# Failure Information

Seems like this function call is overriding the hardhat config prices https://github.com/privacy-scaling-explorations/maci/blob/02cffadfd83e94fb097211c8a64f197fb3b2aeba/contracts/tasks/helpers/Deployment.ts#L325

**Comment by ctrlc03** [comment]
@crisgarner I believe you mentioned this could be closed?

**Comment by crisgarner** [comment]
After testing in multiple networks, seems like the issue is related to the OP testnet in specific times, not a issue in our codebase
