### ISSUE TITLE
re-design projects built with MACI page

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#1613]
Redesign https://maci.pse.dev/projects to look nicer and be easily amended when new projects are available: can ideally re-use semaphore's website code: 
https://semaphore.pse.dev/projects -> https://github.com/semaphore-protocol/semaphore/tree/main/apps/website

**Comment by MukulKolpe** [comment]
Hey @ctrlc03, can I work on this one?

**Comment by ctrlc03** [comment]
> Hey @ctrlc03, can I work on this one?

Hi @MukulKolpe thanks for your interest to help with this. Totally, gonna assign it to you. Let me know if you need any support with it 🙂

**Comment by ctrlc03** [comment]
Hi @MukulKolpe - wanted to check if there was any updates with this task? lmk if we can help

**Comment by MukulKolpe** [comment]
Hey @ctrlc03, sorry for the delay; I got caught up with some work. I'm on it now and will have it ready ASAP.

**Comment by ctrlc03** [comment]
> Hey [@ctrlc03](https://github.com/ctrlc03), sorry for the delay; I got caught up with some work. I'm on it now and will have it ready ASAP.

Hi @MukulKolpe have you got any updates on this one? thanks :)
