### ISSUE TITLE
Deploy subgraph using coordinator service

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci#1629]
As a coordinator I'd like to deploy subgraph using start block, network, maci address and version.

- [x] Add api method with guard to deploy subgraph
- [x] Accept only valid supported networks
- [x] Validate maci address and start block
- [x] Return deployed subgraph url or throw error

**Comment by Dozie2001** [comment]
Hello @0xmad can I get more info old this would love to work on this.

**Comment by 0xmad** [comment]
@Dozie2001 hey, sorry but we need this task done asap.
