### ISSUE TITLE
Research how to send transactions without seed phrase sharing

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci#1630]
As a coordinator I don't want to keep my seed phrase inside coordinator service while signing transactions

- [x] Take a look at account abstraction
- [x] Take a look at seedless wallets

**Comment by ctrlc03** [comment]
Some suggestions from the WAX team: 

```
You could separate the 'write'/txn signing key from the ownership key(s). You would have the privkey for onchain actions in the server, but could revoke/roatate it with the owner key(s) that are somewhere else.

A more advanced version of this would be using a session key module. You would authorize some actions/value for a certain session using your off server key, then pass the session key to the server for use. 
```

**Comment by ctrlc03** [comment]
Possible solution:

1. Deploy [SimpleAccount](https://github.com/eth-infinitism/account-abstraction/blob/develop/contracts/samples/SimpleAccount.sol) managed by EcDSA key in browser (metamask for instance)
2. Sign transaction and send signature and calldata to coordinator service
3. Coordinator service verifies call is from admin and relays using a paymaster client

**Comment by ctrlc03** [comment]
A better solution might be using session keys https://docs.zerodev.app/sdk/permissions/intro 

Actions required: 

1. Deploy contracts without having to sign loads of transactions on a frontend/client 
2. Relay signups and vote messages in MACI offchain design
3. Submit MACI proofs on chain to finalise Polls

Solution with Session keys

1. MACI Deployer creates a Smart Account (It can have an ECDSA validator with a multi sig or passkeys)
2. For deploying contracts the user on the frontend can create a session key valid for a short period of time (5 minutes) for deployment transactions only - encrypt it (RSA) and send it to the coordinator service alongside deployment configuration. The coordinator service uses the session key to deploy the contracts
3. For relaying user messages, the coordinator creates a session key for relaying signup transactions and votes (duration until the end of the poll) - encrypts it with RSA and send it to the coordinator service. The session key can be used to publish the signups and message batches on chain only. After the poll is over the session key cannot be used no more. 
4. To submit proofs on chain to finalise a poll, the coordinator will generate a session key that allows to call the processMessages and tallyVotes functions on MessageProcessor and Tally contract

**Comment by ctrlc03** [comment]
For even better security:
The session key request can also be initiated in the backend https://docs.zerodev.app/sdk/permissions/transaction-automation (this will just make the process a little bit slower)

1. Backend generate session key
2. Backend pulls address from session key account
3. Backend sends address to client
4. Client (and owner of smart account) generates an authorisation for the session key based on some policies
5. Client sends the authorisation to the backend
6. Backend generates wallet client with session key + authorisation
