### ISSUE TITLE
Use zkutil to generate proofs

### ISSUE THREAD

**Issue by weijiekoh** [privacy-scaling-explorations/maci#169]
With circom 0.5.27, it's now possible to use `zkutil` to generate proofs. I had removed `zkutil` when I upgraded to `snarkjs` 0.5.x and when there was an issue with `circom` 0.5.23. That issue has since been fixed. Moreover, `zkutil` is much faster: I tested proof generation for `batchUstCircuit.r1cs` (the test circuit) with `zkutil` and it took 3 seconds. In contrast, `snarkjs` took about 2 minutes.

**Comment by chnejohnson** [comment]
Hi @weijiekoh,

I'm not familiar with zk-snarks, and just want to tally the votes on clr.fund. I have a problem about generate proofs. It works in Aug but fails to generate now. I guess it might be the problem of starting to use zkutil. Could you help me to take a look at my issue on clr.fund?

link: https://github.com/clrfund/monorepo/issues/383#issuecomment-924617136

**Comment by gurrpi** [comment]
Closing since its fixed in https://github.com/privacy-scaling-explorations/maci/pull/180
