### ISSUE TITLE
[Feature Request] Coordiantor helping to send message

### ISSUE THREAD

**Issue by barryWhiteHat** [privacy-scaling-explorations/maci#171]
## Is your feature request related to a problem? Please describe.

At the moment the gas costs on ethereum are very high. Would be nice to reduce the gas cost with some optimizations. The way MACI works at the moment is that users sign up and send commands on chain. We have to use the block chain to avoid censorship of commands by the coordinator. 

## Describe the solution you'd like

Instead of putting all commands on chain we can allow the coordinator to help users as follows. 

1. User wants to publish command
2. User asks teh coordinator to publish for them. 
3. Coordiantor waits will she gets 16 commands. 
4. Coordinator makes a merkle tree with teh 16 commands. 
5. Coordiantor puts just this merkle root in the messageTree
6. Coordinator makes a merkle proof for each of the users who requested message insertion showing that their commands are in the message que. 
7. Users check this proof and are convinced their message will be processed. 

### FAQ

1. Coordinator can do a data availability attack? Well they can just refuse to reveal the result so its does not hcange the guarantees. 
2. Coordinator can only allow users to vote if they like the way they vote. Users can use the on chain `subimitMessage` to avoid this censorship attack.

**Comment by barryWhiteHat** [comment]
If we do https://github.com/appliedzkp/maci/issues/170 then we need to process these messages half way thought processing all messages. So not at the start or at the end but in the middle.

**Comment by weijiekoh** [comment]
> If we do #170 then we need to process these messages half way thought processing all messages. So not at the start or at the end but in the middle.

Hmm, why do you say so? Thanks!

**Comment by ctrlc03** [comment]
Closing this in favour of more of #1623 which will tackle the same problem
