### ISSUE TITLE
Use pnpm monorepo

### ISSUE THREAD

**Issue by niconiahi** [privacy-scaling-explorations/maci#1716]
# Prerequisites

Please answer the following question for yourself before submitting a feature request.

- [ x] I checked to make sure that this request has not already been filed

# Motivation

Currently the repo looks super unorganized, all located at the top most level of the repository. I think that using a monorepo and dividing things up would be very interesting both for development and code maintainability and also for users trying to read the codebase

given this case, I think Lerna wouldn't be neccessary 

# Details

Please describe your feature request in detail.

Make sure that you have reviewed [MACI's Contributor Guidelines](https://maci.pse.dev/docs/contributing)

**Comment by ctrlc03** [comment]
> be very interesting both for development and code maintainability and also for users trying to read the codebase
> 
> given this case, I think Lerna wouldn't be neccessary

Thanks for your feedback, would you suggest to setup something similar to this https://github.com/niconiahi/ethernauta? that looks clean 🙂

**Comment by niconiahi** [comment]
exactly like that

**Comment by ctrlc03** [comment]
@niconiahi  as you saw on #1720 we re-organised the monorepo to be more structured :) We plan to keep using Lerna for now as it works well for publishing packages + the plugins for changelog etc. Would you be happy with considering this as resolved, or are there any other improvements/changes (aside removing lerna) that you suggest?
