### ISSUE TITLE
CircleCI build process for v1 release

### ISSUE THREAD

**Issue by corydickson** [privacy-scaling-explorations/maci#276]
After discussing our current build system with @weijiekoh we have decide to move away from Travis in favor of CircleCI. There are however a few issues, namely with with builds timing out before completion when recompiling circuits. We can increase the timeouts for builds up to an hour but it is possible that we'll hit concurrency resource limits. 

The scripts as they are written pull down precompiled circuits from an Azure instance to mitigate this and allow us to test other packages in the library. To allow for circuit testing, it may be time to use lerna to independently version the `circuits` package and track changes this way, only recompiling when bumped. This issue can track the discussion of various approaches to communicate to down stream dependents when they need to recompile the circuits.

**Comment by weijiekoh** [comment]
Sounds good. What architecture do you have in mind?

Not to prescribe any particular method of doing things but an idea that came to me was using Github Actions to coordinate a 2-step build process.

1. When a new branch/commit/PR is made, trigger a Github Action to do the following:
    a) Look at circuits; if a build for their version exists, skip to step (b). Otherwise, build the circuits, label them with the version number (or their checksum?), and upload them to a private storage space.
    b) Trigger a CI build with tests; said tests will download the circuits from the private storage space.

What do you think? I'm not sure if this is possible or if this is the best approach but happy to discuss further!

**Comment by corydickson** [comment]
I like this approach, and like you said label them according to versions. Maybe do a checksum comparison during step (b)
