### ISSUE TITLE
Ensure subtrees are merged prior to merging the parent State tree

### ISSUE THREAD

**Issue by corydickson** [privacy-scaling-explorations/maci#303]
In order for the final state root to be correctly generated, all subtrees must be merged prior to calling `mergeStateAq`. Currently there is no check in place to ensure this has been completed prior to running the command, thus giving the potential to set the final State root to zero. 

Th solution is to add a new error code to the Poll contract that reverts if subtrees for a given poll have not been merge prior to calling the method above

**Comment by gurrpi** [comment]
Fixed in https://github.com/privacy-scaling-explorations/maci/pull/311
