### ISSUE TITLE
Optimize batch processing of messages

### ISSUE THREAD

**Issue by corydickson** [privacy-scaling-explorations/maci#304]
Related to #269, the `currentSbCommitment` could be skipped and manipulated by a malicious coordinator. This was originally addressed by ensuring in the circuit that the commitment start at zero prior to processing the rest of the commitments.

Nonetheless, rewriting this portion of the contract to no longer skip the `currentMessageBatchIndex` would ensure correct execution regardless.

**Comment by ctrlc03** [comment]
this seems resolved in the latest MessageProcessor contract. please re-open if I'm mistaken
