### ISSUE TITLE
[circuits] benchmark snark proof generation with production-like parameters (e.g. 1024 state leaves and 32 vote options)

### ISSUE THREAD

**Issue by weijiekoh** [privacy-scaling-explorations/maci#31]

**Comment by kendricktan** [comment]
Tested on

```
Macbook Pro (13-inch, 2019) running macOS Catalina, v 10.15.2

(13-inch, 2019, Two Thunderbolt 3 ports)
1.4 GHz Quad-Core Intel Core i5
16 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 645 1536 MB
```

With 10 depth for state and command tree (1024 leaves), and 5 depth for vote options tree (32 vote options)


|Operation|Time(s)|
|-|-|
|Compile| ~13.4|
|Setup|~1710.96|
|Generate Verifier|~1.55|
|WebSnark Proof Generation|TBH|
|Circuit Witness Calculation|TBH|
