### ISSUE TITLE
Fix total spent voice credits decorator

### ISSUE THREAD

**Issue by corydickson** [privacy-scaling-explorations/maci#363]
Currently the decorator only verifies the spent voice credits for a single vote option.

This fix would instead set a public variable to the ppt contract that has the total spent voice credit commitment when processing all of the messages after checking if given these values generate the correct tally commitment. T

he decorator would instead accept the `hashLeftRight(totalSpentCredits, totalSpentCreditsSalt)` and check that this equals the final commitment set in the contract.

**Comment by ctrlc03** [comment]
We now have a `verifySpentVoiceCredits` which accomplishes this.
