### ISSUE TITLE
Check zkey compatibility

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#412]
Given zkeys could generate a invalid proof(see: https://github.com/appliedzkp/maci/issues/390). Checking if given zkeys are valid to a provisioned  `VkRegistry` contract will be useful.

**Comment by ctrlc03** [comment]
is this a duplicate of this or can they be made 1 issue rather than 2? https://github.com/privacy-scaling-explorations/maci/issues/447

**Comment by ctrlc03** [comment]
Seems like this can be closed, please re open if this is a mistake. We can check that the vkeys set in the VkRegistry contract are correct using `checkVerifyingKey`
