### ISSUE TITLE
CI action to run benchmarks

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#422]
see https://github.com/appliedzkp/maci/pull/406/commits/30a9bf61f094a2d0ba5c0569b974423d35bbcc26

**Comment by ctrlc03** [comment]
Closing as completed as we have setup one here: https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/workflows/benchmarks.yml - will need to add more benchmarks throughout all packages.
