### ISSUE TITLE
Check verifier key from parameters and compare to the key on-chain

### ISSUE THREAD

**Issue by auryn-macmillan** [privacy-scaling-explorations/maci#443]
When running `genProofs`, it is possible to generate proofs using the wrong parameters, leading to a scenario where `proveOnChain` will fail. This leads to wasted time and resources computing results that ultimately must be re-computed using the correct parameters.

Ideally, we just use the correct parameters when we run `genProofs`. However, I believe it would be possible for `genProofs` to check that the verifier key in the parameters matches the verifier key on-chain prior to generating any proofs. If there is a mismatch, the process should stop and inform the user of the mismatch.

**Comment by daodesigner** [comment]
There are no "wrong parameters" MACI is a SNARK voting algo that collects encrypted circuit inputs via smart contracts and generates a verifier (written in solidity) capable of checking the calculation succinctly onChain. 

Details of trusted setups, and storage of the params you use for a MACI integration in prod are the responsibility of the coordinator for that round. We encourage anyone doing this to back up those parameters securely, and look into implementing our coordinator service.

**Comment by auryn-macmillan** [comment]
When I say "wrong", I really mean mismatched. It should be doable to crosscheck that the verifier keys in the params correspond with the verifier keys on-chain prior to generating proofs, no?

I get that missmatched keys are a user error issue. Nevertheless it seems like a relatively small change to potential help users like muyself avoid wasted time and resources.

**Comment by auryn-macmillan** [comment]
More concretely:

1. The verifying key (in the zkey file) that is passed to `setVks` is stored on chain. This step happens very soon after the MACI contracts get deployed.
2. `genProofs` should check whether the verifying key on chain matches the verifying key which can be derived from the parameters it uses. This will help the coordinator avoid making a mistake which could cost them lots of time and resources.

**Comment by daodesigner** [comment]
> More concretely:
> 
> 
> 
> 1. The verifying key (in the zkey file) that is passed to `setVks` is stored on chain. This step happens very soon after the MACI contracts get deployed.
> 
> 2. `genProofs` should check whether the verifying key on chain matches the verifying key which can be derived from the parameters it uses. This will help the coordinator avoid making a mistake which could cost them lots of time and resources.

While we appreciate the feedback, MACI0.X will be deprecated soon. The team is focused on MACI1.0 and addressing the root cause of this issue there. If you would like to contribute this feature to MACI0.X please open a PR, I would be happy to review it.
