### ISSUE TITLE
batchUstVerifier and qvtVerifier on the MACI contract are inaccessible externally

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#444]
Hi, 

Is it possible to make these accessible publicly? It'll be useful for debugging purposes. These can still be accessed today using `getStorageAt`, making them public will make it easier to get the values.

```
   // Verifier Contracts
    SnarkVerifier internal batchUstVerifier;
    SnarkVerifier internal qvtVerifier;
```
https://github.com/privacy-scaling-explorations/maci/blob/master/contracts/sol/MACI.sol#L31-L32

**Comment by ctrlc03** [comment]
I'm closing this as it applies to 0.x, feel free to re open if there is a similar need in the v1.x code.
