### ISSUE TITLE
Verify local subsidy `.zkey` file with on-chain verifying key

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#446]
https://github.com/privacy-scaling-explorations/maci/blob/v1/cli/ts/checkVerifyingKey.ts

**Comment by corydickson** [comment]
This issue was raised the in previous audit, almost certain there is support for this somewhere

**Comment by ctrlc03** [comment]
@baumstern Could you elaborate on this issue please?
