### ISSUE TITLE
Allow the coordinator to create a new message tree when the old one is full

### ISSUE THREAD

**Issue by corydickson** [privacy-scaling-explorations/maci#448]
The intention of this issue is to increase the size of messages a MACI poll can handle. 

One fix for this would be to create a nonce of each poll contract that maps to a respective `AccQueue`

**Comment by ctrlc03** [comment]
Closing this as https://github.com/privacy-scaling-explorations/maci/issues/1526 implements a hash chain resulting in unlimited messages per poll
