### ISSUE TITLE
verfiySignature uses 254 bits instead 253

### ISSUE THREAD

**Issue by chaosma** [privacy-scaling-explorations/maci#461]
The field element has maximum of 254 bits to represent. Previously, it only uses 253 bits. This will cause some encrypted message fail to decode and thus halt the whole proof.

```
# circuits/circom/verifySignature.circom
 component snum2bits = Num2Bits(253);
# change to 
 component snum2bits = Num2Bits(254);
```

We still need to make sure other parts are not affected by this change.

**Comment by ctrlc03** [comment]
Closing this as it looks like this change was applied in MACI's `verifySignature` circuit.
