### ISSUE TITLE
Importing `maci-crypto` to a new project requires unnecessary GitHub auth

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#472]
## Problem

Importing `maci-crypto` to a new project would fails when there is no valid GitHub auth; [GitHub requires auth when accessing repo using `git://`](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git). 

### Example error

Addressed from https://github.com/privacy-scaling-explorations/maci/issues/470:

```
$ yarn add maci-crypto

error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/weijiekoh/circomlib.git
Directory: /Users/yuetloo/projects/clrfund/my-key
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Operation timed out
```

## Impact

This makes a frictions to import `maci-crypto` to a third party project, if they didn't set GitHub auth. We can't assume that GitHub auth has been configured on user-side.

* affected version: ~`maci-crypto@1.1.0`

## Solution

using https instead of git in [package.json](https://github.com/privacy-scaling-explorations/maci/blob/v1/crypto/package.json#L17) of maci-crypto. https access to GitHub didn't require an auth

**Comment by ctrlc03** [comment]
This looks fixed, closing for now. Feel free to re-open if that's not the case.

**Comment by yuetloo** [comment]
@ctrlc03 , which version is this fixed in?  We're using v1.1.1 and this is not fixed. We still have to use the work around

```
git config --global url."https://".insteadOf git://
yarn add maci-crypto
```

**Comment by yuetloo** [comment]
Ah, noticed the package.json has been changed to use 'https' instead of 'git' in the dev and master branch. So, I assume this will be available in the next release.

**Comment by ctrlc03** [comment]
> Ah, noticed the package.json has been changed to use 'https' instead of 'git' in the dev and master branch. So, I assume this will be available in the next release.

Exactly, working on finishing all fixes for the bugs you opened + some general improvements and then we'll release the next version. In the meantime, feel free to add any comments to the PRs that are open, or point out if we're missing something that is useful to you guys
