### ISSUE TITLE
Bump `snarkjs` to latest from `0.4.10`

### ISSUE THREAD

**Issue by gurrpi** [privacy-scaling-explorations/maci#513]
Current latest version of `snarkjs` is `0.4.25`. The difference between `0.4.10` and `0.4.25` is usually about dependency updates and plonk related things. 

`maci-circuit` and `maci-cli` uses `snarkjs` for dependency.

* `maci-circuit` uses it to extract verification key of .zkey file and to verify groth16 proof 
* `maci-cli` uses it to generate .zkey file

**Comment by daodesigner** [comment]
What fails on the 0.5.X version?

**Comment by ctrlc03** [comment]
https://github.com/privacy-scaling-explorations/maci/actions/runs/3479192267/jobs/5817439150

I need to look more into it but having issues running test locally sometimes

**Comment by ctrlc03** [comment]
https://github.com/privacy-scaling-explorations/maci/pull/550
