### ISSUE TITLE
Use `snarkjs` API call instead of CLI call

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#514]
There are some `snarkjs` call using shell execution ([e.g.](https://github.com/privacy-scaling-explorations/maci/blob/eb6a8114dac956281a7f5aa0e675a6d97ef06ca9/circuits/ts/index.ts#L90)). But it is error-prone to check execution result. 

[API call example](https://github.com/iden3/snarkjs/blob/master/test/fullprocess.js)

**Comment by sleepyqadir** [comment]
@gurrpi can you assign this issue to me , I can work on it

**Comment by gurrpi** [comment]
> @gurrpi can you assign this issue to me , I can work on it
> 
> 

Cool! Just be aware current active branch is ‘v1’.

**Comment by samajammin** [comment]
FYI @sleepyqadir I'm unassigning this from you. If you'd like to return to this, please let us know!

Also copying over @yuetloo's comments from #746 

> Hi,

> Package managers like npm and yarn have optimization that hoist shared packages to the root level.  When application like clrfund imports MACI packages, and the `snarkjs` package is hoisted up to root level, application will get `path not found` error.

> This is the line for the hardcoded snark.js path
> https://github.com/privacy-scaling-explorations/maci/blob/78609349aecd94186216ac8743d61b1cb81a097f/circuits/ts/index.ts#L8

> Is there any plan to not hardcode the path? For example, use snarkjs api as describe here: > https://github.com/iden3/snarkjs#using-node
