### ISSUE TITLE
Documentation refresh and update

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#531]
Update the documentation and provide more detailed instructions for users.

**Comment by themighty1** [comment]
Hi, there are 2 open PRs which fix the documentation:
https://github.com/privacy-scaling-explorations/maci/pull/520
and
https://github.com/privacy-scaling-explorations/maci/pull/529

**Comment by ctrlc03** [comment]
Thanks for pointing those out, and for submitting #529. The plan is to revamp the documentation and make everything more clear for the V1 release, especially regarding usage steps.

**Comment by ctrlc03** [comment]
TODO:

README(s)
