### ISSUE TITLE
Release article

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#548]
Write a release article walking through the audit and new features.

- [x] Intro, audit and contribute sections - @ctrlc03 
- [x] Subsidy and top up features - @chaosma 
- [x] Review - @daodesigner

**Comment by gurrpi** [comment]
Think we could add release highlights on top of auto-generated [Release Note of GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). The draft will auto-generated when tag pushed to GitHub (e.g. [draft example](https://github.com/privacy-scaling-explorations/maci/releases/tag/untagged-765a25b7eba8276aecfe)). Current configuration for auto-generation is [this](https://github.com/privacy-scaling-explorations/maci/blob/v1/.github/workflows/release.yml#L10-L20).

**Comment by ctrlc03** [comment]
> Think we could add release highlights on top of auto-generated [Release Note of GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes). The draft will auto-generated when tag pushed to GitHub (e.g. [draft example](https://github.com/privacy-scaling-explorations/maci/releases/tag/untagged-765a25b7eba8276aecfe)). Current configuration for auto-generation is [this](https://github.com/privacy-scaling-explorations/maci/blob/v1/.github/workflows/release.yml#L10-L20).

Definitely adding the link to the highlights/changelog in the article sounds good!

**Comment by ctrlc03** [comment]
MACI v1.1.1 released and article published.
