### ISSUE TITLE
Resolve redundancy of contract deployment

### ISSUE THREAD

**Issue by gurrpi** [privacy-scaling-explorations/maci#555]
TODO: resolve redundacy

_Originally posted by @gurrpi in https://github.com/privacy-scaling-explorations/maci/pull/553#discussion_r1037152221_

**Comment by ctrlc03** [comment]
Good shout, although I found that in between txs I had to pull fresh gas fee data to get it to work. Will need to think how to clean up that code

**Comment by gurrpi** [comment]
+ Also unify deploy functions too: https://github.com/privacy-scaling-explorations/maci//blob/v1/contracts/ts/deploy.ts#L120-L179

**Comment by ctrlc03** [comment]
> * Also unify deploy functions too: https://github.com/privacy-scaling-explorations/maci//blob/v1/contracts/ts/deploy.ts#L120-L179

I think this can be unified in the cli. There might be reasons why one would only want to call one function at the time. Or maybe have a deployAll function as well that calls all of them

**Comment by gurrpi** [comment]
> Good shout, although I found that in between txs I had to pull fresh gas fee data to get it to work. Will need to think how to clean up that code

Had thought to solve it by something like following:
```
function invokeDeploy(contractFactory) {
    const gasFees = await signer.provider.getFeeData()

	return await contractFactory.deploy({
        maxFeePerGas: gasFees['maxFeePerGas'],
    })
}
```

**Comment by ctrlc03** [comment]
> > Good shout, although I found that in between txs I had to pull fresh gas fee data to get it to work. Will need to think how to clean up that code
> 
> Had thought to solve it by something like following:
> 
> ```
> function invokeDeploy(contractFactory) {
>     const gasFees = await signer.provider.getFeeData()
> 
> 	return await contractFactory.deploy({
>         maxFeePerGas: gasFees['maxFeePerGas'],
>     })
> }
> ```

Nice this would definitely work

**Comment by gurrpi** [comment]
> > * Also unify deploy functions too: https://github.com/privacy-scaling-explorations/maci//blob/v1/contracts/ts/deploy.ts#L120-L179
> 
> I think this can be unified in the cli. There might be reasons why one would only want to call one function at the time. Or maybe have a deployAll function as well that calls all of them

oh I intended to make just one function like following and call it from business logic:
```
function deployContract(name, args?) {
	const signer = await getDefaultSigner()
    const contractFactory = await ethers.getContractFactory('name', signer)
    const gasFees = await signer.provider.getFeeData()
    return await contractFactory.deploy({
        maxFeePerGas: gasFees['maxFeePerGas'],
    })
}
```

It would get rid of 50+ lines lol

**Comment by ctrlc03** [comment]
> > > * Also unify deploy functions too: https://github.com/privacy-scaling-explorations/maci//blob/v1/contracts/ts/deploy.ts#L120-L179
> > 
> > 
> > I think this can be unified in the cli. There might be reasons why one would only want to call one function at the time. Or maybe have a deployAll function as well that calls all of them
> 
> oh I intended to make just one function like following and call it from business logic:
> 
> ```
> function deployContract(name, args?) {
> 	const signer = await getDefaultSigner()
>     const contractFactory = await ethers.getContractFactory('name', signer)
>     const gasFees = await signer.provider.getFeeData()
>     return await contractFactory.deploy({
>         maxFeePerGas: gasFees['maxFeePerGas'],
>     })
> }
> ```
> 
> It would get rid of 50+ lines lol

yea that's perfect will implement later

**Comment by ctrlc03** [comment]
We need to add the `maxFeePerGas` param to the deployment of pollFactory too, on my latest test deployment it failed while all others succeeded. Adding the following fixed it

```
{
        maxFeePerGas: gasFees['maxFeePerGas']
 }
```
