### ISSUE TITLE
Investigate local e2e test failure

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#559]
Using pre-generated zkeys or generating new zkeys results in failed proof generation on local e2e testing. 
Works fine on CI

**Comment by gurrpi** [comment]
fyi: pre-generated files are compatible with `>v1.0.0` and `<v1.1.0`

**Comment by gurrpi** [comment]
Closing this issue as it has not been able to be reproduced. If the problem persists, please open a new issue or re-open this one.
