### ISSUE TITLE
Run benchmarks to define cost of each ceremony

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#613]
- use infrastructure we will use and simulate end to end creating zkeys calculating from Firebase bandwidth consumed without running the real ceremonies
- define non-circom constraints (length, contributors, backoff, etc)

**Comment by 0xjei** [comment]
Necessary dynamic data for benchmarks (KPIs):
- # of contributors
- # of circuits
- # of constraint sizes

Fixed data for benchamrks:
- Cost x metric (e.g., GB) of AWS / GCP Firebase

Possible questions to answer:
- Is a circuit with twice the constraints and twice the contributions, four times more expensive?. 

Hard:
- Benchmark against past ceremonies (find data about cost/traffic/infra from past ceremonies)
- Easier: focus on past MACI ceremony and et. similar in infra (setup mpc ui).

Output:
- Interactive spreadsheet
- Put on the wiki

**Comment by 0xjei** [comment]
@daodesigner I do not have permission to close this issue. Could you please mark this as completed? Thanks 😊
