### ISSUE TITLE
Decide param combination (and total number of circuits)

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#614]
Goal: figure out what the largest pairwise circuit we can actually generate proofs for is (and if it even makes sense to include in every ceremony).

- [x] check past subsidy benchmarks to estimate largest possible constraint size

Supported param sizes will be: 6-8-3-3 for Tally and process messages, we will punt zkey generation for subsidy circuits of that size until they are optimized or someone requests as they for out at over 100M constraints (ceremony contributions would be way too long to do in parallel every time vs cost )

**Comment by 0xjei** [comment]
Goal: figure out what the largest pairwise circuit we can actually generate proofs for is (and if it even makes sense to include in every ceremony).

**Comment by 0xjei** [comment]
- @gurrpi You probably dealt with this a bit. Do you have any insight?
- @chaosma Did you run any benchmarks yet or did you get stuck?

I am asking this after a quick sync w/ @daodesigner in order to avoid duplicate work/overlaps. Thanks :heart_on_fire:

**Comment by 0xjei** [comment]
Question: Could we do something similar to the maci-benchmark spreadsheet for this issue?

@gurrpi Lmk what do you think

**Comment by gurrpi** [comment]
> Question: Could we do something similar to the maci-benchmark spreadsheet for this issue?
> 
> @gurrpi Lmk what do you think

The purpose of current benchmark is about gas costs and proof generation time. What could we do similarly and what is the focus you want to get out of this issue?

**Comment by 0xjei** [comment]
Hmm, okay. Are you working on pairwise circuit too?

The goal are:
- The largest pairwise circuit for which we can actually generate proofs.
- Understand if makes sense to include that circuit on each ceremony.

**Comment by gurrpi** [comment]
> Hmm, okay. Are you working on pairwise circuit too @gurrpi ?
> 
> I'm asking about potential synergies because the goals here are to:
> 
> * Define the largest pairwise circuit for which we can actually generate proofs.
> * Understand if makes sense to include that circuit on each ceremony.

My current focus is  about ProcessMessages and TallyVotes with 6-8-3-3 params. I suppose constraints should capped up 3.8 M, right? If so, voteOptions of subsidy circuit could not go over than 25(5^2). Then, we would need to check that ProcessMessages & TallyVotes circuits with up to 125 voteOptions and Subsidy circuits with up to 25 voteOptions can be used together.
