### ISSUE TITLE
Audit Smart Contract Changes

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#617]
Contracts changes: 

New (moved out of MACI/Poll/PPT): 

- [ ] MessageProcess.sol
- [ ] Tally.sol
- [ ] Subsidy.sol 

Changed: 

- [ ] MACI.sol
- [ ] Poll.sol
- [ ] Utility.sol 

Steps:

1. review individual contracts/comment on PR (3 story points)
2. check tests  work and add new as required (requires refactoring completed)(3 story points)
3. after initial individual changes/fixes and all refactoring is done, audit all together (logic/contract interaction) (6+ story points depending on changes)
4. review fix if any issues (3 story points)

**Comment by ctrlc03** [comment]
Part 1. done (PR review)
