### ISSUE TITLE
Docs: know which parameter is suitable to for my case(capability of traffic, gas costs, trade-off..)

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#620]

**Comment by daodesigner** [comment]
Depends on benchmarks

**Comment by 0xjei** [comment]
@daodesigner is #613 blocking this issue too?

**Comment by 0xjei** [comment]
Hmm we could, because IMHO the #613 answers the question "Which parameter is suitable for my case?" based on ceremony size (constraints, expected # of participants, and so on) and infrastructure deploy + maintance costs. These factors influence the answer to the question above.

What do you think?

**Comment by gurrpi** [comment]
> Hmm we could, because IMHO the #613 answers the question "Which parameter is suitable for my case?" based on ceremony size (constraints, expected # of participants, and so on) and infrastructure deploy + maintance costs. These factors influence the answer to the question above.
> 
> What do you think? @daodesigner

* gas costs
* proving time

From a MACI operator's perspective, this will help them determine their budget and timeline.

**Comment by 0xjei** [comment]
> > Hmm we could, because IMHO the #613 answers the question "Which parameter is suitable for my case?" based on ceremony size (constraints, expected # of participants, and so on) and infrastructure deploy + maintance costs. These factors influence the answer to the question above.
> > What do you think? @daodesigner
> 
> * gas costs
> * proving time
> 
> From a MACI operator's perspective, this will help them determine their budget and timeline.

Thanks, Dae for the specification.

Yes, I need to take into consideration proving time on #613 too! 

BTW, you could have a look at the spreadsheet to better understand what's going on there on the issue. I think this is going to be useful for the MACI operator. And, again, thanks for the info :)

**Comment by gurrpi** [comment]
> > > Hmm we could, because IMHO the #613 answers the question "Which parameter is suitable for my case?" based on ceremony size (constraints, expected # of participants, and so on) and infrastructure deploy + maintance costs. These factors influence the answer to the question above.
> > > What do you think? @daodesigner
> > 
> > 
> > 
> > * gas costs
> > * proving time
> > 
> > From a MACI operator's perspective, this will help them determine their budget and timeline.
> 
> Thanks, Dae for the specification.
> 
> Yes, I need to take into consideration proving time on #613 too!
> 
> BTW, you could have a look at the spreadsheet to better understand what's going on there on the issue. I think this is going to be useful for the MACI operator. And, again, thanks for the info :)

The sheet looks great. Looking forward to have a sense how much upcoming ceremony will cost soon. :)
