### ISSUE TITLE
Gas benchmarks (clear to user how gas scales for process messages and tally votes as # voters  increases)

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#621]

**Comment by gurrpi** [comment]
target params
* ProcessMessages: 6-8-3-3
* TallyVotes: 6-3-3

scenario
* 1person1vote, all voter cast into same voteOption
* 1person10vote, all voter cast into same voteOption
* (tentative) ..., all voter cast into same voteOption; end of tree? middle of tree?
* (tentative) ..., all voter cast into different voteOptions
* (tentative) ..., ballot casting sequence: round robin..?
