### ISSUE TITLE
npm packages of MACI are working well

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#623]

**Comment by gurrpi** [comment]
npm packages:
- maci-circuits
- maci-cli
- maci-common
- maci-contracts
- maci-core
- maci-crypto
- maci-domainobjs


## Findings

### Broken

maci-cli: https://github.com/privacy-scaling-explorations/maci/issues/640

### Need workaounrd

maci-crypto: https://github.com/privacy-scaling-explorations/maci/issues/470

### Has limitation (only allow to use only `stateTreeDepth` value of 10)

maci-contracts, maci-core: https://github.com/privacy-scaling-explorations/maci/issues/641
