### ISSUE TITLE
QFI as a MACI template

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/maci#633]
- changes to adapt to Q2 plans
- github template for people to fork

@ctrlc03 heads up nabbing this one as I've already started

**Comment by Abuchtela** [comment]
> * changes to adapt to Q2 plans
> * change monorepo structure
> 
> @ctrlc03 heads up nabbing this one as I've already started

[![Build](https://github.com/privacy-scaling-explorations/maci/actions/workflows/build.yml/badge.svg?branch=dev&event=workflow_run)](https://github.com/privacy-scaling-explorations/maci/actions/workflows/build.yml)
