### ISSUE TITLE
`maci-contracts` and `maci-core` packages have a hard-coded `stateTreeDepth` value of 10

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#641]
To change `stateTreeDepth`, User must manually modify values in the source code and build them in the correct order:
https://github.com/privacy-scaling-explorations/maci/wiki/Follow-ups-when-changing-%60stateTreeDepth%60

**Comment by samajammin** [comment]
@yuetloo brought this up as well: https://discord.com/channels/943612659163602974/1164613809730748507/1165694442993369208

Is there a reason this is a hardcoded value in the contract vs. making this a parameter in the constructor that deployers could pass as an argument? Seems painful to require folks to manually change the smart contract source code 😬

**Comment by samajammin** [comment]
Potential short-term solution from @ctrlc03 - hardcode the values to match the [recent ceremony](https://ceremony.pse.dev/projects/Maci%20v1%20Trusted%20Setup%20Ceremony) circuit params (6,8,2,3)

For longer term, seems like we should come up with a better way to set these parameters...

**Comment by ctrlc03** [comment]
> @yuetloo brought this up as well: https://discord.com/channels/943612659163602974/1164613809730748507/1165694442993369208
> 
> Is there a reason this is a hardcoded value in the contract vs. making this a parameter in the constructor that deployers could pass as an argument? Seems painful to require folks to manually change the smart contract source code 😬

yea I think these can be made immutable variables and set in the constructor, basically the only gas cost increase would be when deploying the contract as they need to be passed there.
