### ISSUE TITLE
Request to have `maci.deployPoll()` return the address of the new Poll

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#691]
Currently, it only logs an event with the poll address and id.  Caller will have to get the poll address from the event instead of directly from the function call.  This feature will be useful if `deployPoll` is called from a contract.

https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MACI.sol#L236

**Comment by bibitto** [comment]
Hi, can I work on this issue?

**Comment by bibitto** [comment]
@yuetloo @daodesigner
I've submitted a PR #725

**Comment by bibitto** [comment]
@yuetloo @daodesigner 
Oh, this issue is opening yet :)
