### ISSUE TITLE
[circuits] [crypto] review the signing and signature verification code

### ISSUE THREAD

**Issue by weijiekoh** [privacy-scaling-explorations/maci#70]
Some of the cryptographic code (in `crypto/`) is custom-written and could do with a review.

**Comment by ctrlc03** [comment]
This is handled by [zk-kit eddsa-poseidon package](https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/eddsa-poseidon) and the code was audited as part of semaphore v4 audit: https://semaphore.pse.dev/Semaphore_4.0.0_Audit.pdf
