### ISSUE TITLE
Missing MACI CLI, fetchLog, in v1.1.1

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#723]
In v0.10, the command line `fetchLog` was introduced because `genProofs` would fail (in production) when retrieving event logs from too many blocks.

The `fetchLog` command can retrieve logs in batches which is needed to avoid errors from the node getting too many blocks. See the code here.

https://github.com/clrfund/maci/blob/maci-cli-0.10.2/cli/ts/fetchLogs.ts#L109

**Comment by samajammin** [comment]
Hey @yuetloo - thanks for raising this issue. So you're suggesting to add `fetchLog` back as a CLI command?

@ctrlc03 @0xjei @gurrpi - any idea why this command was removed from MACI v1.x? I don't see any mention of it in the [1.0 release announcement](https://medium.com/privacy-scaling-explorations/release-announcement-maci-1-0-c032bddd2157) or in any [release notes](https://github.com/privacy-scaling-explorations/maci/releases/tag/v1.1.1) (seems we only have those for v1.1.1?). Looks like it was indeed in v0.10: https://github.com/privacy-scaling-explorations/maci/blob/v0.10.1/cli/ts/fetchLogs.ts#L74

**Comment by yuetloo** [comment]
@samajammin yes, I'd like `fetchLog` added back unless someone can explain why it's no longer needed.

**Comment by ctrlc03** [comment]
I'm not familiar with any pre 1.0 code, but I will check if we can put this back to the latest cli package.

**Comment by ctrlc03** [comment]
@yuetloo could you please explain how you were using fetchLogs? trying to get a bit more context on it. Other than that, seems like it shouldn't be a problem to put it back if you need it.

**Comment by yuetloo** [comment]
@ctrlc03 , we use `fetchLogs` to pre-fetch MACI's logs and pass the output to `genProof` through the `log_file` parameter.  Here's our script that uses `fetchLogs` and `genProof`: https://github.com/clrfund/monorepo/blob/develop/contracts/tasks/tally.ts#L73

If we don't pre-fetch MACI's logs, the `genProof()` could fail in the `getLogs()` call because the node could refuse to process a large amount of logs at once.  I've see this error when running the ethStaker round on Arbitrum.  I was using the alchemy node. The MACI address: https://arbiscan.io/address/0x938fedd63c6770ba50266fe4c548a09fd2d1c9f1#code

**Comment by yuetloo** [comment]
@ctrlc03 , there's a bug in the v0.10.1 code which included duplicate logs because the fromBlock and toBlock parameters of `getLogs` are inclusive. We fixed it in our fork by incrementing the startBlock of next batch of request in the loop in this commit:

https://github.com/privacy-scaling-explorations/maci/commit/074f51f3d9a69fa052207af0df613763d91cab65

**Comment by ctrlc03** [comment]
@yuetloo thanks for explaining, I'll try to add it back tomorrow and test it out. 
Btw would you mind dropping me a text on discord/twitter/tg (username is the same as here) - would love to chat more about how you are using Maci and how we can help you more

**Comment by ctrlc03** [comment]
I see now why it was removed, within the maci-contracts package we have this: https://github.com/privacy-scaling-explorations/maci/blob/78609349aecd94186216ac8743d61b1cb81a097f/contracts/ts/genMaciState.ts which generates a local maci state and with that one we can export all params needed for the circuits. I do see that this does not do any batching, just fetches all logs in one go, I'll see if I can make it work in batches too

**Comment by yuetloo** [comment]
@ctrlc03 , I think that's the original logic, https://github.com/privacy-scaling-explorations/maci/blob/v0.10.1/cli/ts/utils.ts#L105, it exports the params in 1 batch when generating maci states.

I think pre-fetch logic (fetchLog) was added later because we hit error in production. In the line I copied, it will generate the MACI states using pre-fetched log if available, otherwise, fallback to the original logic which is to fetch all the logs in 1 batch.

**Comment by ctrlc03** [comment]
> @ctrlc03 , I think that's the original logic, https://github.com/privacy-scaling-explorations/maci/blob/v0.10.1/cli/ts/utils.ts#L105, it exports the params in 1 batch when generating maci states.
> 
> I think pre-fetch logic (fetchLog) was added later because we hit error in production. In the line I copied, it will generate the MACI states using pre-fetched log if available, otherwise, fallback to the original logic which is to fetch all the logs in 1 batch.

Got it. What I think we'll do for now, is to add batching to the genMaciState function which is used now in genProos, related PR is here https://github.com/privacy-scaling-explorations/maci/pull/758 - does that sound good to you?
