### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#728]
I think we could simplify the documentation by consolidating areas of repetition/overlap

A couple places I noticed

Installation/configuration:
- https://github.com/privacy-scaling-explorations/maci#local-development-and-testing
- https://github.com/privacy-scaling-explorations/maci/blob/master/docs/installation.md

Testing:
- https://github.com/privacy-scaling-explorations/maci#testing
- https://github.com/privacy-scaling-explorations/maci/blob/master/docs/testing.md

Perhaps we move most documentation out of the GH README (& instead push folks to the documentation website)? Or vice versa?

Seems these resources are also inconsistent at times (e.g. one testing page mentions running Hardhat, one does not), so perhaps they're due for an update 😄

**Comment by samajammin** [comment]
Also discovered we have some documentation in the wiki:
https://github.com/privacy-scaling-explorations/maci/wiki

Perhaps that should be moved into a central location as well...

**Comment by ctrlc03** [comment]
Closing as fixed on #826
