### ISSUE TITLE
Documentation formatting bug?

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#729]
Not certain but I suspect there's bugs around displaying mathematical formulas...

e.g. on https://privacy-scaling-explorations.github.io/maci/primitives.html

![Image 2023-10-15 at 12 32 06](https://github.com/privacy-scaling-explorations/maci/assets/8097623/eaaccb5c-488f-4d29-8d81-5aac28c82895)

Is the documentation supposed to be able to render LaTeX or something similar?

**Comment by samajammin** [comment]
FWIW we've had success in past projects (e.g. https://github.com/ethereum/cryptography-research-website) with KaTeX:
https://katex.org/

**Comment by ctrlc03** [comment]
> FWIW we've had success in past projects (e.g. https://github.com/ethereum/cryptography-research-website) with KaTeX: https://katex.org/

suggesting we use this issue to track researching how to preview this documentation before a PR is merged, so errors like this are spotted before merging.
