### ISSUE TITLE
Documentation: update "Trusted setup" page

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#730]
https://privacy-scaling-explorations.github.io/maci/trustedsetup.html

This page could use a refresh - @ctrlc03 @0xjei I assume we should update this page to reference:
- https://github.com/privacy-scaling-explorations/DefinitelySetup/
- https://github.com/privacy-scaling-explorations/p0tion
- https://ceremony.pse.dev/

LMK what you think

**Comment by ctrlc03** [comment]
Yea good shout, and in a few days we can add all links to the ceremony final artifacts, plus maybe a small guide on how to verify that the final zKey was computed using the public beacon value for transparency.
