### ISSUE TITLE
Should only allow the owner of the MACI contract to deploy a new poll

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#748]
As shown in the test case in PR https://github.com/privacy-scaling-explorations/maci/pull/747, anyone can deploy a poll, not just the owner of the MACI contract.

The deployPoll() function should check and only allow owner to deploy poll.
https://github.com/clrfund/maci-v1/blob/fix/maci-issue/contracts/contracts/MACI.sol#L236

**Comment by ctrlc03** [comment]
I get what you mean there, one could frontrun a poll deployment and basically the owner would need to re-deploy the MACI contract to run a poll. Should be fine to add the `onlyOwner` modifier. I'll add some comments on your PR, thank you
