### ISSUE TITLE
refactor crypto package

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#753]
Refactor the crypto package:
- [x] shift from one file to multiple organized files
- [x] add more typedoc docs
- [x] ensure generateRandomBabyJubValue does not throw but runs until a valid value is generated
- [x] separate types
- [x] separate tests and move supporting functions to utils
- [x] fix inconsistencies between BigInt and bigint types
- [x] fix various (repo-wide) ts bugs due to missing types declarations

**Comment by samajammin** [comment]
@ctrlc03 for future reference, it'd be great to provide a bit more detail in the issue desc, e.g.
- break out package into multiple organized files
- add typedoc docs
- add code comments
- etc.

Ideal scenario being that any core dev could pick the issue up & knows what to do.

**Comment by ctrlc03** [comment]
> @ctrlc03 for future reference, it'd be great to provide a bit more detail in the issue desc, e.g.
> 
> * break out package into multiple organized files
> * add typedoc docs
> * add code comments
> * etc.
> 
> Ideal scenario being that any core dev could pick the issue up & knows what to do.

Totally, I've pasted the description in the issue body here
