### ISSUE TITLE
Establish GH development process for repo

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#757]
**Update: see https://github.com/privacy-scaling-explorations/maci/issues/757#issuecomment-1828646712 for latest proposal & todos**

Let's align on various processes for how to manage this project & GH repo.

- branches
- versioning & publishing packages (#807)
- audits
- PRs & issues
  - conditions to merge a PR (& branch protection rules)
  - issue triage & prioritization process
  - commit conventions
  - label conventions

- [ ] Create GH discussion for this

Once established, let's document this for our contributors.

**Comment by samajammin** [comment]
@ctrlc03 added a description here. Feel free to edit.

**Comment by samajammin** [comment]
@ctrlc03 @baumstern @0xjei attempting to summarize the proposal in terms of updates to our GitHub processes from our discussions. Please LMK what you think!

### Branches

- `main` branch for ongoing development
- tags for releases
- feature/fix branches which are to be merged to the main branch after approval
- (for now use dev and main until we finish refactoring and get code audited then can get rid of main)

Updates to make

- [ ]  Update `master` branch to `main`
- [ ]  Update `main` as default branch
- [ ]  Delete `dev` branch

### Conventions

- branch name
    - feat / fix / chore / docs
    - i.e. fix/contracts feat/new-feature docs/contracts chore/run-prettier
- commits style
    - use commitizen https://commitizen-tools.github.io/commitizen/
    - fix(package-name) - fixed x in y because of z + longer description
    - commit using git cz for the interactive commit prompt

Updates to make

- [ ]  Update README/documentation on this
    - i.e. what defines a feature / bug fix / chore / documentation
- [ ]  Contributors optionally install Commitizen (https://github.com/commitizen-tools/commitizen#installation)

### Publishing releases

- all releasing must be done from the code approved and merged to the main branch
- publishing is done via the CI → https://github.com/privacy-scaling-explorations/maci/wiki/CI-Pipeline#tag-push

Updates to make

- [x]  CI workflow: https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/workflows/release.yml
- [ ]  Document how this works (https://maci.pse.dev/docs/ci-pipeline#tag-push)

### Opening a PR

- add the appropriate label
- add a list of changes
- reference the appropriate issue using closing keywords (e.g. `Fixes #issueNumber`) in the PR description
- PR approvals
    - 1 approval for merge into `main`
    - 2 approvals for release
    - CI must be green before merge
- ensure branch is deleted after the PR is merged
- when reviewing a PR, go over to the issue(s) that the PR is trying to fix and assign yourself as the reviewer
    - after reviewing a PR we should try to explicitly submit a review to either "approve" it or "request changes" to avoid ambiguity

Updates to make

- [x]  Update GH settings to “Automatically delete head branches”
- [ ]  Create GH PR template (of sections to fill out) e.g. https://github.com/ethereum/ethereum-org-website/blob/dev/.github/PULL_REQUEST_TEMPLATE.md
- [ ]  Update README/documentation on this

### Opening a Issue

- add the appropriate label
- when beginning to work on a issue, assign yourself to it
    - if an external contributor, comment under the issue and we will assign you

Updates to make

- [ ]  Create GH issue templates
    - [ ]  Bug report
    - [ ]  Feature request (e.g. https://github.com/ethereum/ethereum-org-website/blob/dev/.github/ISSUE_TEMPLATE/feature_request.yaml)
- [ ]  Update README/documentation on this

### Versioning

- https://hackmd.io/@samajammin/maci-versioning
- minor version → no breaking changes
- major version → breaking changes
    - changing a circuit is a breaking change as it requires a new trusted setup ceremony

Updates to make

- [ ]  Add documentation on our approach to versioning (i.e. add https://hackmd.io/@samajammin/maci-versioning to a page in https://maci.pse.dev/docs/)

**Comment by 0xmad** [comment]
It will be useful to enforce commit messages checks for PRs.
We use commitlint for cryptkeeper. Here is a job example. https://github.com/CryptKeeperZK/crypt-keeper-extension/blob/main/.github/workflows/commitlint.yml
