### ISSUE TITLE
release 1.1.3

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#769]
Release and thoroughly test version 1.1.3:

- [ ] fixes requested by clr.fund
- [ ] ts refactoring
- [ ] smart contract refactoring done by Chao earlier in the year
- [ ] 6,8,2,3 params

**Comment by samajammin** [comment]
Thanks for this @ctrlc03! 

Question re: this issue - could this just be a milestone? e.g. is this work different than the "MACI v1.1.1 refactor": https://github.com/privacy-scaling-explorations/maci/milestone/5

I think generally it'd be ideal to have a release (e.g. this 1.1.3) be a list of issues to complete.

> smart contract refactoring done by Chao earlier in the year

Is there a branch/PR for this? Or what's this referring to?

**Comment by ctrlc03** [comment]
Fair point here, I think we can close this off and keep the milestone as it better represents the effort for the refactoring (which would end up in the release of 1.1.3)
