### ISSUE TITLE
Better documentation in smart contracts and solidity docs

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#770]
- [ ] Add https://github.com/OpenZeppelin/solidity-docgen
- [ ] ensure [NatSpecs](https://docs.soliditylang.org/en/latest/natspec-format.html) comments are formatted correctly
- [ ] Add generated docgen pages to website

**Comment by ctrlc03** [comment]
> @ctrlc03 mind expanding on your thoughts here? What do you mean by "better"? 😄 

Fairs 😆 updated the description

**Comment by ctrlc03** [comment]
> > Add https://github.com/OpenZeppelin/solidity-docgen
> 
> @ctrlc03 is the thinking here that we'd add the output of this into our docs? Perhaps we turn the "Smart Contracts" page (https://maci.pse.dev/docs/contracts) into a directory?

Depends how easy is to do that? 
My initially thought was that given that solidity docgen would generate an output like typedoc (so all automated), it might be better to host it the way we host typedoc (on its own page), and keep the contracts.md file for more detailed information, which we can manually edit.

**Comment by samajammin** [comment]
> My initially thought was that given that solidity docgen would generate an output like typedoc (so all automated), it might be better to host it the way we host typedoc (on its own page), and keep the contracts.md file for more detailed information, which we can manually edit.

Cool. I'm good with that, at least to begin with 👍
