### ISSUE TITLE
Identification of the Coordinator Role

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#773]
We need clarity on the coordinator's role. There's been overlap, and we need to set things straight.

**Tasks:**

1. Define Coordinator Role:
        * List main tasks and responsibilities.
        * Identify challenges tied to these tasks.

2. Distinguish Responsibilities:
        * Separate core duties from secondary tasks.

**Goal:**
Get a clear picture of the coordinator's role to guide our future work.

**Comment by samajammin** [comment]
> There's been overlap

What do you mean by this? Overlap with what, other MACI roles? Where has there been overlap, e.g. in our documentation?

**Comment by ctrlc03** [comment]
@baumstern bumping this: some info here would be appreciated

**Comment by baumstern** [comment]
Check this for context: #417. Basically, tasks like proof generation, tally, and onchain proving are distinct and separate functions

**Comment by ctrlc03** [comment]
Could this be closed by this: https://maci.pse.dev/docs/overview/workflow#roles ?
We also have workstreams open for a coordinator service: proof service and deployer service

**Comment by baumstern** [comment]
> Could this be closed by this: https://maci.pse.dev/docs/overview/workflow#roles ? We also have workstreams open for a coordinator service: proof service and deployer service

Sure!
