### ISSUE TITLE
Dependency refresh

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#793]
Before release perform the following:

- [x] npm audit 
- [x] upgrade as much as possible to newest version of the same library 
- [x] remove any unnecessary dependency to keep packages slim

**Comment by baumstern** [comment]
fyi: NPM audit has addressed in https://github.com/privacy-scaling-explorations/maci/pull/806

**Comment by ctrlc03** [comment]
Closing as #965 #972 #963 #944 #806 and all other refactor work resolved this.
