### ISSUE TITLE
Unify Quote Usage

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#810]
The codebase uses a mix of single and double quotes. They need to be unified for consistent styling.

**Comment by baumstern** [comment]
### @samajammin 's thought

              Another consistency nitpick - looks like you're using a mix of single quotes & double quotes. Do we have a convention on this? I don't have a strong preference... just that we be consistent

_Originally posted by @samajammin in https://github.com/privacy-scaling-explorations/maci/pull/585#discussion_r1379720199_

**Comment by baumstern** [comment]
I don't have a strong preference either, @ctrlc03 what do you think?

**Comment by ctrlc03** [comment]
> I don't have a strong preference either, @ctrlc03 what do you think?

let's stick to C convention? " for strings? this way it's also easier in case we are writing some text somewhere which needs an ' - no need to escape it. automatic linter for it and we just forget about it :)
