### ISSUE TITLE
cross-platform MACI

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#814]
Currently, it is not possible to fully use MACI (e2e process) on a non-intel machine. This is due to the use of rapidsnark which uses Intel assembly for faster zk-SNARK proof generation. 

To solve this, we could check on which architecture we are running , if running on ARM, then use Snarkjs with the wasm file to generate a proof.

Steps:

- [x] add fullProve declaration to snarkjs.d.ts
- [x] change genProof function on circuits ts code
- [x] add function to check for architecture
- [x] change genProofs to accept new arguments and new validation + new genProof function signature
- [x] change test scripts to check the system we are running on and pass the correct args
- [x] test it all

**Comment by samajammin** [comment]
Solved in #817
