### ISSUE TITLE
Update mentions of circom-helper

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#815]
We recently replaced this library in #784

We still mentioned `circom-helper` here:
https://maci.pse.dev/installation.html#requirements

> The `libgmp-dev` `nlohmann-json3-dev` `nasm` and `g++` Debian/Ubuntu
  packages. They are needed to run `circom-helper`, which in turn is used to
  develop and test zk-SNARK circuits.

Should this whole block be removed?

If so, also installation commands?

> ```bash
> sudo apt-get install build-essential libgmp-dev libsodium-dev nasm git
> ```

I'm seeing this packages used in some workflows, so not exactly sure what can be safely removed here...

**Comment by samajammin** [comment]
@ctrlc03 @baumstern perhaps you folks know the answer here 😄

**Comment by ctrlc03** [comment]
> @ctrlc03 @baumstern perhaps you folks know the answer here 😄

I believe build-essentials and a couple of others are needed to compile c++ witness generators on ubuntu systems. I will see how we can properly differentiate the different requirements based on systems - might want to merge this first: https://github.com/privacy-scaling-explorations/maci/pull/817

**Comment by ctrlc03** [comment]
Fixed in #826
