### ISSUE TITLE
Refactoring of Circuits package

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#816]
Refactor the package:

- [x] clean up unused dependencies
- [x] update dependencies
- [x] docs improvements
- [x] monolith file to multiple files
- [x] circuits comments
- [x] usage instructions
- [x] build scripts cleanup

**Comment by samajammin** [comment]
>  docs improvements

I'd love to see the [circuits doc page](https://maci.pse.dev/circuits.html) updated/expanded to cover for each circuit:
- What is the high-level purpose of this circuit? Why is a circuit needed here, vs. using some other process (e.g. on-chain execution)? i.e. what problem is this circuit uniquely solving, that couldn't be solved without a SNARK?
- How does this circuit interact with the rest of the MACI system? e.g. is the circuit changing any smart contract state? Or just returning values that are used elsewhere?
- How does the circuit fit into the lifecycle of MACI (e.g. which step of a poll)?
- How is the circuit executed (e.g. via a CLI command? If so, which)? Which role is interacting with the circuits (I think it's the coordinator for all, correct?)
- What are the inputs for the circuit? What are the outputs? I think the parameters are already mentioned in docs, but could use expansion
- How & where are proofs generated for this circuit? How & where are the proofs verified (e.g. on-chain?)?
- How to test? How are the tests set up?

Some general information I think would be useful for n00bs like me:
- Link to beginner resources for devs who are completely new to SNARKS & circuits
- Quick intro of Circom & links to learning resources (e.g. Circom docs, `circom-helper` repo)
- Link to the circuits package in the repo (i.e. https://github.com/privacy-scaling-explorations/maci/tree/master/circuits)

Perhaps the docs work can be a separate issue? LMK what you think @ctrlc03

**Comment by ctrlc03** [comment]
> docs work can be a separate issue?

totally missed this! definitely can add all of the above, I would probably keep it all in one PR as anyways there really isn't much that's gonna change code wise, just one typescript file being a little bit re-organized 🙂
