### ISSUE TITLE
Consolidate testing libraries across the monorepo

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#818]
Currently we are using different testing libraries across the project. Given that the circuits use mocha (circom_tester) and hardhat for the contracts test use mocha too, it seems wise to stop using jest across all other TS packages in favour of Mocha. The changes will be minimum. 

- [x] remove jest @types/jest 
- [x] install mocha ts-mocha @types/mocha chai @types/chai
- [x] fix all tests
- [x] change test scripts
- [x] bonus: run all tests in one command from the root of the monorepo

This would also help with some issues arising when running typedoc on the repo

**Comment by samajammin** [comment]
Love it! I suspect this will solve some Jest <> Mocha interface clashing issues I've been facing in this branch: https://github.com/privacy-scaling-explorations/maci/pull/755#issuecomment-1791460192

My (naive) preference would have been to use Jest over Mocha, given it seems to be overall more popular & better maintained, but if Mocha & Hardhat use Mocha, that sounds like a great reason to just roll with that!

**Comment by ctrlc03** [comment]
> Love it! I suspect this will solve some Jest <> Mocha interface clashing issues I've been facing in this branch: [#755 (comment)](https://github.com/privacy-scaling-explorations/maci/pull/755#issuecomment-1791460192)
> 
> My (naive) preference would have been to use Jest over Mocha, given it seems to be overall more popular & better maintained, but if Mocha & Hardhat use Mocha, that sounds like a great reason to just roll with that!

Yea I see the point of using Jest, we can always switch back and solve the issues between mocha<>jest in case mocha is missing some features that we will need in the future. So far it seems like we can run everything as we did befre with ts-mocha  🙂

**Comment by samajammin** [comment]
Fixed by https://github.com/privacy-scaling-explorations/maci/pull/819
