### ISSUE TITLE
Fix outdated website

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#820]
The changes of document has recently introduced by https://github.com/privacy-scaling-explorations/maci/pull/779. But website shows the outdated version in https://maci.pse.dev/audit.html (https://maci.pse.dev/trustedsetup.html as well).

**Comment by samajammin** [comment]
> The changes of document has recently introduced by https://github.com/privacy-scaling-explorations/maci/pull/779

@baumstern I'm not sure what this means... could you clarify what you mean here?

I'm guessing you meant documentation? Is the gist of this issue: we've updated the documentation (e.g. in #779), but the website has not updated to reflect those changes? So seemingly there's a bug with our GH workflow to deploy the documentation?
