### ISSUE TITLE
Extend CI Pipeline to include macOS support

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#839]
### Objective
Our current CI pipeline is tailored exclusively for Ubuntu. This issue proposes extending our CI support to include macOS, ensuring broader compatibility

**Comment by ctrlc03** [comment]
> ### Objective
> Our current CI pipeline is tailored exclusively for Ubuntu. This issue proposes extending our CI support to include macOS, ensuring broader compatibility

Is there a mac arm gh runner that you know of?

**Comment by baumstern** [comment]
> > ### Objective
> > Our current CI pipeline is tailored exclusively for Ubuntu. This issue proposes extending our CI support to include macOS, ensuring broader compatibility
> 
> Is there a mac arm gh runner that you know of?

yes, but currently they are only provided in the paid GitHub plans: : https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners

**Comment by ctrlc03** [comment]
> > > ### Objective
> > > Our current CI pipeline is tailored exclusively for Ubuntu. This issue proposes extending our CI support to include macOS, ensuring broader compatibility
> > 
> > 
> > Is there a mac arm gh runner that you know of?
> 
> yes, but currently they are only provided in the paid GitHub plans: : https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners

right, thanks for confirming

**Comment by ctrlc03** [comment]
Seems like mac runners are now free to use for public repos!!
