### ISSUE TITLE
Make linter stricter and unified

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci#845]
As a developer, I'd like to have linter configuration for all the packages with predefined rules.

### Acceptance criteria:
- [x] Add linter config package
- [x] Get rid of `public` keyword for classes
- [x] Apply for `circuits`
- [x] Apply for `cli`
- [x] Apply for `common`
- [x] Apply for `contracts`
- [x] Apply for `core`
- [x] Apply for `crypto`
- [x] Apply for `domainobjs`
- [x] Apply for `integrationTests`
- [x] Apply for `server`
- [x] Apply for `website`
- [x] Fix solidity lint errors
- [ ] Add readme docs for linter

**Comment by samajammin** [comment]
Request - as part of this work, please update our README/docs with how the linting setup & configuration works
