### ISSUE TITLE
Epic: Release MACI v1.2.0

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#856]
_This is a meta-issue to capture our near-term roadmap to release an improved version of MACI in Q1 2024_

# MACI Refactoring plan

## Problem

Our core team has identified that the codebase has lots of opportunity for improvement. It's not well documented. It could be less complex & better organized. It's a bit slow, inefficient, repetitive, bug prone. As it stands, it's difficult for developers who want to integrate MACI to do so.

A recent [report on private voting](https://app.streameth.org/devconnect/progcrypto/session/the_state_of_private_voting__report) confirmed our internal assessments, rating MACI low (2/5) on "ease of integration".

## Methodology

For this release, the focus will be on improving developer experience (DX) to solve many issues with the current "ease of integration". We will not make any breaking changes to the code, we will not change the existing functionality, we will not change how users interact with MACI. The primary goal is to clean up the codebase to improve DX & onboarding to the project.

## Goals

**1. Improve code quality**

- overall make the codebase more readable & accessible
- refactor each package
  - break out monolith files: types, utils, classes, tests etc.
  - add comments with TypeDoc to explain code
  - add type declaration files
- style guide w/ linter & auto-formatting

**2. Improve tooling:**

- more up to date versions
  - update to latest minor versions
- use native tools (for instance test smart contracts with Hardhat directly)
  - e.g. we don’t use Hardhat for testing - run using Jest (vs. Hardhat’s mocha)
- use maintained libraries not out of data dependencies
  - e.g. circom_tester vs circom_helper
- simplify tooling
  - e.g. consolidate testing libraries (vs. using both Mocha & Jest)

**3. Revamp documentation**

- consolidate disparate docs/wikis/resources
- add versioned docs
- add generated docs (TypeDoc & Solidity NatSpec)
- build out our own markdown files
- find a solution to host everything
- add graphs and flowcharts to explain concepts
- add integration guide

## Milestone

See the "MACI v1.1.1 refactor" milestone to track the individual issues within this epic:
https://github.com/privacy-scaling-explorations/maci/milestone/5

**Comment by ctrlc03** [comment]
> Pulling some Discord discussion here around getting an audit before/after this release. @baumstern suggested:
> 
> > We can tag v1.2.0-rc after finishing this milestone(https://github.com/privacy-scaling-explorations/maci/milestone/5), and then release v1.2.0 once we complete the audit.
> 
> Thoughts on this @ctrlc03 @0xmad ?

Sounds good to me

**Comment by samajammin** [comment]
Branch has been created for audit 🚀 thanks @ctrlc03 

https://github.com/privacy-scaling-explorations/maci/tree/audit/v1.2.0

**Comment by ctrlc03** [comment]
https://github.com/privacy-scaling-explorations/maci/releases/tag/v1.2.0 🥳
