### ISSUE TITLE
MessageProcessor and Tally should use a state variable for Poll rather than it being a function parameter

### ISSUE THREAD

**Issue by ctrlc03** [privacy-scaling-explorations/maci#862]
Currently, both MessageProcessor.sol and Tally.sol accept a Poll contract object as a parameter on various function calls. This could lead to abuse by the coordinator. Instead, the poll address should be a state variable for better accountability and safety

**Comment by samajammin** [comment]
> This could lead to abuse by the coordinator

How? Mind expanding on this?

**Comment by ctrlc03** [comment]
Sure thing. A coordinator could pass arbitrary values within certain functions:

* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Tally.sol#L118 
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Tally.sol#L107
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Tally.sol#L163
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Subsidy.sol#L85
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/Subsidy.sol#L140
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L58
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L140
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L194
* https://github.com/privacy-scaling-explorations/maci/blob/dev/contracts/contracts/MessageProcessor.sol#L235

and be able to update sensitive values, or prove that a computation was done correctly by having these arbitrary contracts return bogus values.
On the other hand, if these contracts were deployed with their respective addresses as state variables, the parameter would not be needed and the coordinator would not be able to pass on arbitrary values. Also it would make the process more transparent.
 
Possible solution:

deploy the three (four counting subsidy) together in this order:

* Poll
* MP (take Poll address in the constructor)
* Tally (take Poll and MP addresses in the constructor)
* Subsidy (take Poll and MP addresses in the constructor)
