### ISSUE TITLE
Create documentation page(s) from A Technical Introduction to MACI 1.0

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#878]
@kcharbo3 created this amazing post last year: [A Technical Introduction to MACI 1.0](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a)

The post covers two main topics:

1. [System Overview](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#6ca2)
a. [Roles](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#f130)
b. [Vote Overriding and Public Key Switching](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#0b6f)
c. [zk-SNARKs](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#aa08)

2. [Workflow](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#357c)
a. [Sign Up](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#a35f)
b. [Publish Message](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#37df)
c. [Process Messages](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#493a)
d. [Tally Votes](https://medium.com/privacy-scaling-explorations/a-technical-introduction-to-maci-1-0-db95c3a9439a#56b5)

I think we should incorporate this content within our documentation so that we can keep it up to date as MACI evolves. Kyle gave me the go-ahead to do this - thanks Kyle! 

I suggest we create 2 new docs pages:
1. System overview - explain the "roles" of the system and how they interact with MACI, as well as key pieces of the system (like vote overriding & key switching)
2. Workflow - explain the lifecycle of MACI: deploying, running a poll, finalizing results, both the "happy path" for a simple case, as well as a more complex example (e.g. if a user switches keys & overrides their votes)

Open to feedback here - input appreciated!

**Comment by samajammin** [comment]
Self-assigning, happy to take this on.

**Comment by ctrlc03** [comment]
@samajammin is this completed with #1223 ?

**Comment by samajammin** [comment]
Yes, fixed in https://github.com/privacy-scaling-explorations/maci/pull/1223
