### ISSUE TITLE
Add TypeDoc to search

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/maci#884]
Currently the TypeDoc section (https://maci.pse.dev/typedoc) is not searchable. The files are not indexed in the site search.

As a user I'd like to use site search for packages or function names.

I'm also noticing the individual HTML pages don't have individual routes. The content if fetched from different HTML files but everything is served at https://maci.pse.dev/typedoc/ - these may need to be updated to individual routes in order to support site search indexing.

Not sure if a separate or related bug, but I can't `cmd + K` to pull up site search while the the https://maci.pse.dev/typedoc page. I can on initial load but not after interacting with the page (e.g. clicking on a function name).

**Comment by kittybest** [comment]
I don't know if this is what you're looking for:

https://github.com/privacy-scaling-explorations/maci/assets/9023842/cb9a9bc4-41e7-4413-850b-046afb6c8133

Or do you need a route to keep the search history? such as `https://maci.pse.dev/typedoc#AccQueue`?
