### ISSUE TITLE
Tests improvements

### ISSUE THREAD

**Issue by 0xmad** [privacy-scaling-explorations/maci#892]
As a developer I'd like to have stable meaningful tests to check the behaviour and correctness.
For example, I'd get rid of checks like (expect not to be undefined/null), add more tests in terms of refactoring plan and support code coverage reports.

**Comment by ctrlc03** [comment]
Had opened this couple of days back to track improvements of tests https://github.com/privacy-scaling-explorations/maci/issues/869

**Comment by 0xmad** [comment]
Ok, good, let's close this one.
