### ISSUE TITLE
Clarification needed on `numSignUps` Count in MACI.sol

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/maci#962]
In `MACI.sol`, `numSignUps` currently includes an additional count unrelated to actual user signups. This discrepancy can lead to confusion regarding the accurate number of user signups

Releated issue: https://github.com/privacy-scaling-explorations/maci/issues/947

**Comment by samajammin** [comment]
@baumstern just to confirm, this is in reference to the changes introduced in https://github.com/privacy-scaling-explorations/maci/pull/948 ?

**Comment by baumstern** [comment]
> @baumstern just to confirm, this is in reference to the changes introduced in #948 ?

yes
