### ISSUE TITLE
Set EmptyBallotRoot values at contract deploy time instead of at build time

### ISSUE THREAD

**Issue by yuetloo** [privacy-scaling-explorations/maci#973]
# Prerequisites

Please answer the following question for yourself before submitting a feature request.

- [x] I checked to make sure that this request has not already been filed

# Motivation

The EmptyBallotRoot values must match the value of STATE_TREE_DEPTH in MACI.sol.  Since STATE_TREE_DEPTH is set when deploying MACI, EmptyBallotRoot values should be set at deploy time as well to make sure the correct values are deployed with the contract.

# Details

The [maci-contracts](https://www.npmjs.com/package/maci-contracts/v/0.0.0-ci.45668db) npm package published by the CI job (e2e.yml) always publishes the EmptyBallotRoots with STATE_TREE_DEPTH=10, the default when the STATE_TREE_DEPTH is not provided to the compileSol.sh.

As a result, the npm package `maci-contracts` is published with a EmptyBallotRoot.sol that only works with STATE_TREE_DEPTH=10.

This also means that the `maci-contracts` package is not suitable to use with the circuit 6-8-2-3 from the ceremony.

**Comment by ctrlc03** [comment]
> Please answer the following question for yourself before submitting a feature request.
> 
> * [x]  I checked to make sure that this request has not already been filed

Great point, was just thinking about this today! @0xmad what you suggest here, should we add the ceremony param [here](https://github.com/privacy-scaling-explorations/maci/blob/dev/.github/workflows/release.yml#L37) so we publish the one compiled with 6 as stateTreeDepth?

**Comment by 0xmad** [comment]
@ctrlc03 I think we can use github vars and if we need to change it in future we just change the var and trigger the build.

**Comment by ctrlc03** [comment]
> @ctrlc03 I think we can use github vars and if we need to change it in future we just change the var and trigger the build.

I like this!
